# ===========================================================================
# Project:   TestApp
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :'sai', :required => [:sproutcore]
config :all, :required => [:'sai', :sproutcore]